appointments/urls.py
from django.conf.urls import patterns, url
from appointments import views
from django.views.generic import TemplateView

urlpatterns = patterns('',
#    url(r'^$', views.IndexView.as_view(), name='index'), 
#    # Month Example: /2013/11/04
#    url(r'^(?P<year>\d{4})/(?P<month>\d+)/(?P<day>\d+)', 
#        views.AppointmentDayArchiveView.as_view(), 
#        name='appointment_day_numeric'),
#    # Week Example: /2013/week/44
#    url(r'^(?P<year>\d{4})/week/(?P<week>\d+)$',
#        views.AppointmentWeekArchiveView.as_view(),
#        name="appointment_week"),
#    # Day Example: /2013/11
#    url(r'^(?P<year>\d{4})/(?P<month>\d+)$',
#        views.AppointmentMonthArchiveView.as_view(month_format='%m'),
#        name="appointment_month_numeric"),
    
    url(r'^$', TemplateView.as_view(template_name="appointments/appointment_index.html"), name='index'),
    url(r'^events$', views.AppointmentJson.as_view(), name='eventsjson'),
    url(r'^events/changes$', views.AppointmentChanges.as_view(), name='eventschanges'),

    url(r'^(?P<pk>\d+)', views.DetailView.as_view(), name='detail'),

    url(r'^create', views.AppointmentCreate.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)', views.AppointmentUpdate.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)', views.AppointmentDelete.as_view(), name='delete'),

)

notes/urls.py
from django.conf.urls import patterns, url
from notes import views


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)', views.NoteDetailView.as_view(), name='detail'),
    )

petra/urls.py
from django.conf.urls import patterns, include, url
from petra import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^$', TemplateView.as_view(template_name="base.html")),
    url(r'^appointments/', include('appointments.urls', namespace='appointments')),
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^invoices/', include('invoices.urls', namespace='invoices')),
    url(r'^notes/', include('notes.urls', namespace='notes')),
)

appointments/models.py
from decimal import Decimal
from django.db import models
from customers.models import Customer
from pricings.models import Pricing
from django.core.urlresolvers import reverse

class Appointment(models.Model):
    title     = models.CharField('Title', max_length=200)
    notes     = models.CharField('Notes', max_length=500)
    customer  = models.ForeignKey(Customer)
    start_date = models.DateTimeField('start date')
    end_date   = models.DateTimeField('end date')
    has_occured = models.NullBooleanField(null=True, blank=True)
    pricing = models.ForeignKey(Pricing)
    invoice = models.ForeignKey('invoices.Invoice', null=True, blank=True)
    
    def get_feed_template(self):
        return "feeditems/feeditem_appointment.html"

    def get_sort_date(self):
        return self.start_date

    def get_filteritem(self):
        return "appointment"

    def __unicode__(self):
        return self.title
    
    def is_invoiced(self):
        if(self.invoice): return True
        else: return False

    def get_duration(self):
        time_delta = self.end_date - self.start_date
        return time_delta.total_seconds()

    def get_duration_hours(self):
        hours = self.get_duration() /60 /60
        hours = round(hours, 2)
        return hours

    def get_duration_minutes(self):
        mins = self.get_duration() /60 
        mins = round(mins, 2)
        return mins


    def get_appointment_price(self):
        hours = self.get_duration_hours()
        rate = self.pricing.rate_hour
        result = Decimal(hours) * rate
        return round(result, 2)

    def get_absolute_url(self):
        # redirect after successfull form submit to created appointment
        return reverse('appointments:index')

appointments/views.py
from appointments.models import Appointment

import datetime, calendar, json
from datetime import timedelta
import pprint

from django.views import generic
from django.views.generic.base import TemplateView, View
from django.views.generic.dates import DayArchiveView, WeekArchiveView, MonthArchiveView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import get_object_or_404
from django.http import HttpResponse

class DetailView(generic.DetailView):
    # default template_name = <app name>/<model name>_detail.html
    model = Appointment

class AppointmentCreate(CreateView):
    model = Appointment
    # default template name: appointment_form.html
    def get_success_url(self):
        success_url = reverse('appointments:detail', args=(self.object.id,))
        print success_url
        return success_url
    def get_context_data(self, **kwargs):
        context = super(AppointmentCreate, self).get_context_data(**kwargs)
        context['action'] = 'create'
        return context

class AppointmentUpdate(UpdateView):
    model = Appointment
    # default template name: appointment_form.html
    def get_success_url(self):
        success_url = reverse('appointments:detail', args=(self.object.id,))
        print success_url
        return success_url
    def get_context_data(self, **kwargs):
        context = super(AppointmentUpdate, self).get_context_data(**kwargs)
        context['action'] = 'update'
        return context

class AppointmentDelete(DeleteView):
    model = Appointment
    success_url = reverse_lazy('appointments:index')


"""
Transform an appointment entity to an event object as needed by fullcalendar 
Event object specification: http://arshaw.com/fullcalendar/docs/event_data/Event_Object/
"""
def appt_as_event(appt):
    event = {}
    event["id"] = appt.pk
    event["title"] = appt.title
    # start = event.start_date.strftime("%Y-%m-%d") # %H:%M:%S")
    event["start"] = calendar.timegm(appt.start_date.utctimetuple())
    event["end"] = calendar.timegm(appt.end_date.utctimetuple())
    event["allDay"] = False
    event["url"] = reverse('appointments:detail', args=(appt.pk,))
    event["editable"] = True
    event["notes"] = appt.notes
    return event

def appts_as_events(appts):
    return [appt_as_event(appt) for appt in appts]

class AppointmentJson(View):
    def get(self, request):
        start = request.GET['start']
        start_date = datetime.date.fromtimestamp(int(start))
        end = request.GET['end']
        end_date = datetime.date.fromtimestamp(int(end))
        appts = Appointment.objects.filter(start_date__gte=start_date, end_date__lte=end_date)
        events = appts_as_events(appts)
        return HttpResponse(json.dumps(events), content_type="application/json")

def parse_params_as_ints(request, param_names):
    return {param: int(request.POST[param]) for param in param_names}

class AppointmentChanges(View):
    def post(self, request):
        appt = get_object_or_404(Appointment, pk=request.POST['apptId'])
        deltas = parse_params_as_ints(request, ['startDayDelta', 'startMinuteDelta', 'endDayDelta', 'endMinuteDelta'])
        if (deltas['startDayDelta'] != 0) or (deltas['startMinuteDelta'] != 0):
            appt.start_date = appt.start_date + timedelta(days=deltas['startDayDelta']) + timedelta(minutes=deltas['startMinuteDelta'] )
        if (deltas['endDayDelta'] != 0) or (deltas['endMinuteDelta'] != 0):
            appt.end_date = appt.end_date + timedelta(days=deltas['endDayDelta']) + timedelta(minutes=deltas['endMinuteDelta'])
        if any([v != 0 for v in deltas.values()]):
            appt.save()
        event = appt_as_event(appt)
        return HttpResponse(json.dumps(event), content_type="application/json")

templates/appointments/appointment_confirm_delete.html
<h3>Are you sure you want to delete {{appointment}}?</h3>
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Yes"/>
  <input type="button" value="No" onclick="window.history.go(-1);"/>
</form>

templates/appointments/appointment_detail.html
{% extends "base.html" %}
{% block content %}
Customer: {{ appointment.customer }} <br/>
Notes: {{ appointment.notes }} <br/>
Duration: {{ appointment.get_duration_hours }} hours <br/>
Price per hour: {{ appointment.pricing.rate_hour }} <br/>
Total Price: {{ appointment.get_appointment_price }} <br/>
{% if appointment.is_invoiced %}
Has been invoiced
{% else %}
Not invoiced
{% endif %}
<br/>
Occured: {{ appointment.has_occured }}
<br/>
<span>
  <a href="{% url 'appointments:update' appointment.pk  %}">[ edit ]</a>
</span>
<span>&nbsp &nbsp &nbsp</span>
<span>
  <a href="{% url 'appointments:delete' appointment.pk  %}">[ delete ]</a>
</span>
{% endblock %}

templates/appointments/appointment_form.html
{% extends 'base.html' %}
{% block content %}
{% if action == "create" %}
<h2> Neuen Termin erstellen </h2>
{% elif action == "update" %}
<h2>Termin bearbeiten</h2>
{% else %}
<h2>THIS SHOULD NEVER HAPPEN!!</h2>
{% endif %}

<form id="create-appointment-form" method="post">
{% csrf_token %}

<table>
  {{ form.as_table }}
</table>
<input id="appointment-save" class="btn btn-primary" type="submit" value="Anlegen" />
</form>

{% load static %}
<script type="text/javascript" src="{% static 'appointments/create_appointment.js' %}"></script>
{% endblock content %}

templates/appointments/appointment_index.html
{% extends "base.html" %}

{% load static %}

{% block extra_js %}
<!-- fullCalendar -->
<script type='text/javascript' src="{% static 'vendor/fullcalendar/fullcalendar.js' %}"></script>
<!-- calendar handling etc. -->
<script type='text/javascript' src="{% static 'appointments/utils.js' %}"></script>
<script type="text/javascript" src="{% static 'appointments/create_appointment.js' %}"></script>
<script type='text/javascript' src="{% static 'appointments/appointment.js' %}"></script>
{% endblock extra_js %}

{% block content %}
<div>
  <a class="btn btn-primary" href="{% url 'appointments:create' %}">Termin erstellen</a>
</div>
<br/>

<div id="cal-title">
  <span class="fc-header-title" style="display: none;">
    <h2></h2>
  </span>
</div>

<div id="calendar"></div>

<div id="appointment-dialog"></div>

{% endblock content %}