invoices/urls.py
from django.conf.urls import patterns, url
from invoices import views

urlpatterns = patterns('',
        url(r'^create', views.create_invoice, name='create_invoice'),
        url(r'^(?P<pk>\d+)', views.DetailView.as_view(), name='detail'),
        url(r'^', views.InvoiceListView.as_view(), name='list'),
        )

notes/urls.py
from django.conf.urls import patterns, url
from notes import views


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)', views.NoteDetailView.as_view(), name='detail'),
    )

petra/urls.py
from django.conf.urls import patterns, include, url
from petra import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^$', TemplateView.as_view(template_name="base.html")),
    url(r'^appointments/', include('appointments.urls', namespace='appointments')),
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^invoices/', include('invoices.urls', namespace='invoices')),
    url(r'^notes/', include('notes.urls', namespace='notes')),
)

invoices/models.py
from django.db import models
from customers.models import Customer
from appointments.models import Appointment

class Invoice(models.Model):
    from_date = models.DateTimeField('from date')
    until_date   = models.DateTimeField('until date')
    customer = models.ForeignKey(Customer)

    def get_appointments(self):
        return Appointment.objects.filter(invoice=self.id)

    def get_total(self):
        sum = 0
        for apt in self.get_appointments():
            sum += apt.get_appointment_price()
        return sum

invoices/views.py
import datetime
import json
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.core.serializers.json import DjangoJSONEncoder
from appointments.models import Appointment
from customers.models import Customer
from invoices.models import Invoice

def get_appointments(from_date, until_date, customer):
    appoints = Appointment.objects.filter(start_date__gte=from_date) \
            .filter(start_date__lte=until_date) \
            .filter(customer=customer.id) \
            .filter(invoice=None) \
            .filter(has_occured=True)
    return appoints


k_from_date = 'from_date'
k_until_date = 'until_date'
k_customer = 'for_customer'
k_appointments = 'appointments_to_invoice'
k_save_invoice = 'save_invoice'
k_total_sum = 'total_sum'
date_format = '%Y-%m-%d'

def from_session(session):
    from_date = datetime.datetime.strptime(session[k_from_date], date_format) 
    until_date = datetime.datetime.strptime(session[k_until_date], date_format)
    until_date += datetime.timedelta(days=1)
    customer = Customer.objects.get(pk=session[k_customer])
    appointments = get_appointments(from_date, until_date, customer) 
    sum = 0
    for apt in appointments:
        sum += apt.get_appointment_price()
    return {
            k_from_date: from_date, 
            k_until_date: until_date,
            k_customer: customer,
            k_appointments: appointments,
            k_total_sum: sum
           }
    

def create_invoice(request):
    ## Parameters for Template
    appointments_to_invoice = None 
    total_sum = -1
    customers = Customer.objects.all()
    error_message = None
    success_message = None

    if request.method == 'GET':
        #Not really anything to do here ...
        print 'GET'

    elif request.method == 'POST':
        if k_save_invoice in request.POST and request.POST[k_save_invoice]:
            dict = from_session(request.session)
            invoice = Invoice(
                        from_date=dict[k_from_date],
                        until_date=dict[k_until_date],
                        customer=dict[k_customer]
                        )
            invoice.save()
            for apt in dict[k_appointments]:
                apt.invoice = invoice
                apt.save()

            print 'SAVE'
        #Selection of appointments for invoice
        elif k_from_date in request.POST  and request.POST[k_from_date] and \
                k_until_date in request.POST and request.POST[k_until_date] and \
                k_customer in request.POST:
                    print request.POST
                    request.session[k_from_date] = request.POST[k_from_date]
                    request.session[k_until_date] = request.POST[k_until_date]
                    request.session[k_customer] = request.POST[k_customer]
                    dict = from_session(request.session)
                    appointments_to_invoice = dict[k_appointments]
                    total_sum = dict[k_total_sum]
                    success_message = 'Appointments for {0} between {1} and {2}' \
                            .format(dict[k_customer], dict[k_from_date], dict[k_until_date])
        else:
            error_message = 'Please specify customer, start and end date!'
#
#               sum = 0
#                for apt in appointments_to_invoice:
#                    sum += apt.get_appointment_price()
#                total_sum = sum
#                success_message = 'Invoice items for {0} between {1} and {2}:' \
        #        .format(for_customer, from_date, until_date)
    return render(request, 'invoices/create_invoice.html',
            {
                'error_message': error_message,
                'success_message': success_message,
                'customers': customers,
                'appointments_to_invoice': appointments_to_invoice,
                'total_sum':total_sum
                })



class DetailView(generic.DetailView):
    model = Invoice

class InvoiceListView(generic.list.ListView):
    context_object_name = 'invoice_list'
    model = Invoice

templates/invoices/create_invoice.html
{% extends 'base.html' %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type='text/css' href="{% static 'invoices/create_invoice.css' %}"/>
{% endblock extra_css %}

{% block extra_js %}
	<script type="text/javascript" src="{% static 'invoices/create_invoice.js' %}"></script>
{% endblock extra_js %}

{% block content %}

<form action="{% url 'invoices:create_invoice' %}" method="post">
  {% csrf_token %}
  <label for="for_customer">Customer:</label>
  <select name="for_customer" id="for_customer">
    {% for cust in customers %}
    <option value="{{ cust.id }}">{{ cust }}</option>
    {% endfor %}
  </select>
  <p>
  <label for="from_date">From: </label>
  <input type="text" id="from_date" name="from_date">
  </p>
  <p><label for="until_date">Until: </label><input type="text" id="until_date" name="until_date"></p> 
  {% if error_message %}
  <p class="error">{{ error_message }}</p>
  {% endif %}
  <input type="submit"/>
</form>

{% if appointments_to_invoice %}
<form action="{% url 'invoices:create_invoice' %}" method="post">
  {% csrf_token %}
  <br/>
  <h3>{{ success_message }}</h3>
  <table border="1">
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Customer</th>
      <th>occured</th>
      <th>pricing</th>
      <th>duration</th>
      <th>Amount</th>

    </tr>
    {% for apt in appointments_to_invoice %}
    <tr>
      <td> {{ apt.start_date }} </td>
      <td> {{ apt.end_date }} </td>
      <td> {{ apt.customer }} </td>
      <td> {{ apt.has_occured }} </td>
      <td> {{ apt.pricing.rate_hour }} </td>
      <td> {{ apt.get_duration_hours }} </td>
      <td> {{ apt.get_appointment_price }} </td>

    </tr>
    {% endfor %}
    <tr>
      <td colspan="6">TOTAL:</td>
      <td>{{ total_sum }} </td>
    </tr>
  </table>
  <input type="hidden" name="save_invoice" value="True">
  <input type="submit" value="Save this invoice">
</form>
{% else %}
No appointments selected
{% endif %}
{% endblock content %}

templates/invoices/invoice_detail.html
{% extends 'base.html' %}

{% block content %}
<h3>Invoice No.: {{ invoice.id }} </h3>
<p>Customer: {{invoice.customer }} </p>
<table border="1">
  <tr>
    <th>Start date</th>
    <th>End date</th>
    <th>Customer</th>
    <th>occured</th>
    <th>pricing</th>
    <th>duration</th>
    <th>Amount</th>

  </tr>
  {% for apt in invoice.get_appointments %}
  <tr>
    <td> {{ apt.start_date }} </td>
    <td> {{ apt.end_date }} </td>
    <td> {{ apt.customer }} </td>
    <td> {{ apt.has_occured }} </td>
    <td> {{ apt.pricing.rate_hour }} </td>
    <td> {{ apt.get_duration_hours }} </td>
    <td> {{ apt.get_appointment_price }} </td>

  </tr>
  {% endfor %}
  <tr>
    <td colspan="6">TOTAL:</td>
    <td>{{ invoice.get_total }} </td>
  </tr>
</table>

{% endblock content %}

templates/invoices/invoice_list.html
{% extends 'base.html' %}
{% block content %}
<ul>
{% for inv in invoice_list %}
<li><a href="{% url 'invoices:detail' inv.id %}">{{ inv.id }} sum: {{ inv.get_total }}i</a></li>
{% endfor %}

</ul>
{% endblock content %}