customers/urls.py
from django.conf.urls import patterns, url
from customers import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'), 
    url(r'^feed/(?P<cust>\d+)/', views.CustomerFeedView.as_view(), name='customerfeed'),
)

invoices/urls.py
from django.conf.urls import patterns, url
from invoices import views

urlpatterns = patterns('',
        url(r'^create', views.create_invoice, name='create_invoice'),
        url(r'^(?P<pk>\d+)', views.DetailView.as_view(), name='detail'),
        url(r'^', views.InvoiceListView.as_view(), name='list'),
        )

notes/urls.py
from django.conf.urls import patterns, url
from notes import views


urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)', views.NoteDetailView.as_view(), name='detail'),
    )

petra/urls.py
from django.conf.urls import patterns, include, url
from petra import views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^$', TemplateView.as_view(template_name="base.html")),
    url(r'^appointments/', include('appointments.urls', namespace='appointments')),
    url(r'^customers/', include('customers.urls', namespace='customers')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^invoices/', include('invoices.urls', namespace='invoices')),
    url(r'^notes/', include('notes.urls', namespace='notes')),
)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Disable default mobile browser virtual viewport which is usually wider than the screen -->
    <!-- For more details see e.g. https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag -->
    <!-- Bootstrap also requires this -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} This is PeTraaaa! {% endblock %}</title>

    <!-- ----------- -->
    <!-- Stylesheets -->
    <!-- ----------- -->

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">

    <!-- Vendor -->
    <link rel="stylesheet" href="{% static 'vendor/jquery/jquery-ui-1.10.3-smoothness.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/jquery/jquery.simple-dtpicker.css' %}" />
    <link rel='stylesheet' href="{% static 'vendor/fullcalendar/fullcalendar.css' %}" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />

    <!-- Own Stylesheets -->

    {% block extra_css %} {% endblock extra_css %}

  </head>  
  <body>

    <!-- ---------- -->
    <!-- Javascript -->
    <!-- ---------- -->

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery-1.10.2.js' %}"></script>
    <!-- jQuery dev version fixt die 'event.returnValue is deprecated.' Warnung. Good to know -->
    <!-- <script type='text/javascript' src="http://code.jquery.com/jquery-git1.js"></script> -->
 
    <!-- jQuery Extensions -->
    <!-- jQuery UI Requirements: -->
        <!-- fullcalendar needs jQuery UI Draggable and Resizable (http://arshaw.com/fullcalendar/docs/event_ui/Requirements/) -->
        <!-- <script type='text/javascript' src="{% static 'vendor/jquery/jquery-ui.custom.min.js' %}"></script> -->
        <!-- jQuery UI dialog for appointment creation in calendar -->
    <!-- Use full jQuery UI for development, determine required plugins for production -->
    <script src="{% static 'vendor/jquery/jquery-ui-1.10.3.js' %}"></script>

    <!-- jQuery UI datepicker for appointment and invoice creation (seems to be not included in jquery-ui-min.js) -->
    <script type='text/javascript' src="{% static 'vendor/jquery/jquery.simple-dtpicker.js' %}"></script> 
 
    <!-- Bootstrap -->
    <script type='text/javascript' src=" {% static 'vendor/bootstrap/js/bootstrap.min.js' %} "></script>

    <!-- Own Javascript -->
    {% block extra_js %} {% endblock extra_js %}

    <!--
    <div id="header">
       <img src="{% static 'p.png' %}" style="float:left;">
       <div style="float:left; font-size:60px; line-height:110px;">eTra 0.2</div>
       <div id="topnavigation" style="clear:both">
         {% block topnavigation %}
         <ul class="inline">
           <li><a href="{% url 'customers:index' %}">Kunden</a></li>
           <li><a href="{% url 'appointments:index' %}">Termine</a></li>
           <li><a href="{% url 'customers:customerfeed' 1 %}">Kundendetails</a></li>
           <li><a href="{% url 'invoices:create_invoice' %}">Rechnung erstellen</a></li>
         </ul>
         {% endblock %}
       </div>
    </div>
    -->
    
     <nav class="navbar navbar-default" role="navigation">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapseable">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>

         <a class="navbar-brand">Petra</a>

       </div>
       <div class="collapse navbar-collapse" id="navbar-collapseable">
         <ul class="nav navbar-nav">
           <li><a href="{% url 'customers:index' %}">Kunden</a></li>
           <li><a href="{% url 'appointments:index' %}">Termine</a></li>
           <li><a href="{% url 'customers:customerfeed' 1 %}">Kundendetails</a></li>
           <li><a href="{% url 'invoices:create_invoice' %}">Rechnung erstellen</a></li>
         </ul>
       </div>
     </nav>

    <div id="content">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>